#!/bin/zsh
# 本地预览 docs/ 下的页面（如剧情时间轴的手稿浮层需要 http 才能读文件）。
# 用法：在仓库根目录跑 ./serve-docs，自动打开剧情时间轴，Ctrl-C 停服。
URL="http://localhost:8000/docs/%E5%89%A7%E6%83%85%E6%97%B6%E9%97%B4%E8%BD%B4.html"
(sleep 1 && open "$URL") &>/dev/null &
exec python3 -m http.server 8000
