;; 反应由玩家上一回合的最后一次路线行动决定，枪口与次数均明牌。
(define 完了? #f)
(define 瞄准 '无)
(define 上次路线 '无)
(define 货棚走过? #f)
(define 栈桥走过? #f)
(define 诱饵用过? #f)
(define 货棚 (make-clock "货棚出口" 5 'gauge "满格脱身并保住底片；本回合只能走一次。"))
(define 栈桥 (make-clock "栈桥出口" 4 'gauge "满格脱身，但底片会被海水泡坏；本回合只能走一次。"))
(define 封锁 (make-clock "封锁" 4 'gauge "回合末加1；扔诱饵另加1；满格无路可走。"))
(define (结束! result text)
  (if 完了? (error "枪口认路：重复结束") #t)
  (set! 完了? #t)
  (spotlight! "脱身" text)
  (end-encounter result))
(define (检查!)
  (cond ((货棚 'full?) (结束! '带底片脱身 "你钻出货棚，底片还干干净净地贴在胸口。"))
        ((栈桥 'full?) (结束! '弃底片脱身 "你跳进海里。人游到了岸边，底片却泡烂了。"))
        ((封锁 'full?) (结束! '困住 "探照灯从两头照过来。出口全被堵住了。"))))
(define (走! route clk n)
  (if (equal? route '货棚) (set! 货棚走过? #t) (set! 栈桥走过? #t))
  (set! 上次路线 route)
  (if (equal? route 瞄准) (spend-actor-composure! 'player 2) #f)
  (clk 'advance! n)
  (if (= n 0) (spend-actor-composure! 'player 1) #f)
  (检查!))
(define (路线卡 name route clk)
  (node name :subtitle (if (equal? route 瞄准) "枪口在这里：另花2冷静；中进1，好进2。" "本回合一次；坏停步，中进1，好进2。")
    :requires (list (req-die)) :resolve (roll 'sharpness
      (outcome (lambda () (走! route clk 0)))
      (outcome (lambda () (走! route clk 1)))
      (outcome (lambda () (走! route clk 2))))))
(define-opponent-rule "枪手认路"
  (lambda () (not 完了?))
  (lambda ()
    (set! 瞄准 上次路线)
    (set! 货棚走过? #f)
    (set! 栈桥走过? #f)
    (封锁 'advance! 1)
    (检查!)))
(define (on-encounter-enter)
  (play-dialogue!
    (line "世界" "底片拍下了交易。你要带它逃出去，实在不行就保住自己。")
    (line "世界" "枪声打碎了货棚门口的灯。底片还在你的口袋里。")
    (line "世界" "枪手下回合会盯住你最后走的路。货棚保底片，栈桥只保命。")))
(define (on-encounter-collapse) (collapse-result '倒下))
(define (get-render-data)
  (container "枪口认路"
    (append
      (list (note-node "标注：目标" "目标：带片脱身"
        "走货棚能保住底片；走栈桥能活着离开，但底片会泡坏。封锁前逃出任一路。"))
      (clock-nodes (货棚 'render-data) (栈桥 'render-data) (封锁 'render-data))
      (list (note-node "标注：枪口" "枪手盯着"
              (cond ((equal? 瞄准 '货棚) "货棚。走这条路额外花2冷静。")
                    ((equal? 瞄准 '栈桥) "栈桥。走这条路额外花2冷静。")
                    (else "还没看准；走任一路都没有额外冷静代价。")))
            (note-node "标注：下轮" "下回合枪口"
              (cond ((equal? 上次路线 '货棚) "货棚。再走栈桥可改变下一回合的枪口。")
                    ((equal? 上次路线 '栈桥) "栈桥。再走货棚可改变下一回合的枪口。")
                    (else "没有认准路线。"))))
      (if 货棚走过? '() (list (路线卡 "穿过货棚" '货棚 货棚)))
      (if 栈桥走过? '() (list (路线卡 "绕到栈桥" '栈桥 栈桥)))
      (if 诱饵用过? '()
          (list (node "扔响空罐" :subtitle "一次性：清掉当前枪口；封锁加1。"
            :requires (list (req-die)) :resolve (instant (lambda ()
              (set! 诱饵用过? #t) (set! 瞄准 '无) (封锁 'advance! 1) (检查!))))))
      (list (instant-action "举起双手" (lambda () (结束! '投降 "你举起双手。枪手拿走了底片。")))))))
