(load-file "scripts/research/common.scm")
(define 储备 (make-clock "储备" 4 'gauge "备料坏0、中1、好2；回合末减1。窗口兑换为两倍进度。"))
(define (开窗?) (or (= 连续窗口 1) (odd? (期限 'current))))
(define (研究附记) (list (储备 'current) (开窗?)))
(define (兑现!)
  (let ((k (储备 'current))) (储备 'reset!) (研究推进! (* k 2))))
(define-opponent-rule "窗口轮换"
  (lambda () (not 完了?))
  (lambda () (储备 'advance! -1) (期限 'advance! 1) (研究检查!)))
(define (get-render-data)
  (研究盘面 (if (= 连续窗口 1) "每轮均可兑现；储备每格换2进度，回合末减1。直接推进随时可做。" "第2、4轮可兑现；储备每格换2进度，回合末减1。直接推进随时可做。")
    (append (clock-nodes (储备 'render-data))
      (list (note-node "标注：窗口" "窗口" (if (开窗?) "本轮开放，兑现可重复。" "本轮关闭，下轮开放。"))))
    (append
      (list
        (node "直接推进" :subtitle "坏0、中1、好2，随时可做。" :requires (list (req-die))
          :resolve (roll 'knowledge (outcome (lambda () (研究推进! 0)))
            (outcome (lambda () (研究推进! 1))) (outcome (lambda () (研究推进! 2)))))
        (node "备料" :subtitle "坏储备0；中加1；好加2。" :requires (list (req-die))
          :resolve (roll 'knowledge (outcome (lambda () #f))
            (outcome (lambda () (储备 'advance! 1))) (outcome (lambda () (储备 'advance! 2))))))
      (if (and (开窗?) (not (储备 'empty?)))
        (list (node "兑现" :subtitle "一骰：两倍储备推进，然后清空。" :requires (list (req-die))
          :resolve (instant 兑现!))) '()))))
